src/java/controlador/ProveedoresController.java
package controlador;

import entidad.Proveedores;
import controlador.util.JsfUtil;
import controlador.util.JsfUtil.PersistAction;
import sesion.ProveedoresFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "proveedoresController")
@SessionScoped
public class ProveedoresController implements Serializable {

    @EJB
    private sesion.ProveedoresFacade ejbFacade;
    private List<Proveedores> items = null;
    private Proveedores selected;

    public ProveedoresController() {
    }

    public Proveedores getSelected() {
        return selected;
    }

    public void setSelected(Proveedores selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ProveedoresFacade getFacade() {
        return ejbFacade;
    }

    public Proveedores prepareCreate() {
        selected = new Proveedores();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/agenda").getString("ProveedoresCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/agenda").getString("ProveedoresUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/agenda").getString("ProveedoresDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Proveedores> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/agenda").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/agenda").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<Proveedores> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Proveedores> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Proveedores.class)
    public static class ProveedoresControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ProveedoresController controller = (ProveedoresController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "proveedoresController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Proveedores) {
                Proveedores o = (Proveedores) object;
                return getStringKey(o.getIdProveedores());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Proveedores.class.getName()});
                return null;
            }
        }

    }

}

web/proveedores/Actua.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProveedoresActuaDlg" widgetVar="ProveedoresActuaDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda.ActuaProveedoresTitle}">
            <h:form id="ProveedoresActuaForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{proveedoresController.selected != null}">
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_idProveedores}" for="idProveedores" />
                        <p:inputText id="idProveedores" value="#{proveedoresController.selected.idProveedores}" title="#{agenda.ActuaProveedoresTitle_idProveedores}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_idProveedores}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{proveedoresController.selected.nombre}" title="#{agenda.ActuaProveedoresTitle_nombre}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_nombreContacto}" for="nombreContacto" />
                        <p:inputText id="nombreContacto" value="#{proveedoresController.selected.nombreContacto}" title="#{agenda.ActuaProveedoresTitle_nombreContacto}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_nombreContacto}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_telefonoContacto}" for="telefonoContacto" />
                        <p:inputText id="telefonoContacto" value="#{proveedoresController.selected.telefonoContacto}" title="#{agenda.ActuaProveedoresTitle_telefonoContacto}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_telefonoContacto}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_telefonoEmpresa}" for="telefonoEmpresa" />
                        <p:inputText id="telefonoEmpresa" value="#{proveedoresController.selected.telefonoEmpresa}" title="#{agenda.ActuaProveedoresTitle_telefonoEmpresa}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_telefonoEmpresa}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_emailContacto}" for="emailContacto" />
                        <p:inputText id="emailContacto" value="#{proveedoresController.selected.emailContacto}" title="#{agenda.ActuaProveedoresTitle_emailContacto}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_emailContacto}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_domicilio}" for="domicilio" />
                        <p:inputText id="domicilio" value="#{proveedoresController.selected.domicilio}" title="#{agenda.ActuaProveedoresTitle_domicilio}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_domicilio}"/>
                        <p:outputLabel value="#{agenda.ActuaProveedoresLabel_idUsuarios}" for="idUsuarios" />
                        <p:selectOneMenu id="idUsuarios" value="#{proveedoresController.selected.idUsuarios}" required="true" requiredMessage="#{agenda.ActuaProveedoresRequiredMessage_idUsuarios}">
                            <f:selectItem itemLabel="#{agenda.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsuariosItem"
                                           itemValue="#{idUsuariosItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{proveedoresController.update}" value="#{agenda.Save}" update="display,:ProveedoresListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ProveedoresActuaDialog');"/>
                    <p:commandButton value="#{agenda.Cancel}" onclick="ProveedoresActuaDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/proveedores/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProveedoresCreateDlg" widgetVar="ProveedoresCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda.CreateProveedoresTitle}">
            <h:form id="ProveedoresCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{proveedoresController.selected != null}">
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_idProveedores}" for="idProveedores" />
                        <p:inputText id="idProveedores" value="#{proveedoresController.selected.idProveedores}" title="#{agenda.CreateProveedoresTitle_idProveedores}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_idProveedores}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{proveedoresController.selected.nombre}" title="#{agenda.CreateProveedoresTitle_nombre}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_nombreContacto}" for="nombreContacto" />
                        <p:inputText id="nombreContacto" value="#{proveedoresController.selected.nombreContacto}" title="#{agenda.CreateProveedoresTitle_nombreContacto}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_nombreContacto}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_telefonoContacto}" for="telefonoContacto" />
                        <p:inputText id="telefonoContacto" value="#{proveedoresController.selected.telefonoContacto}" title="#{agenda.CreateProveedoresTitle_telefonoContacto}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_telefonoContacto}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_telefonoEmpresa}" for="telefonoEmpresa" />
                        <p:inputText id="telefonoEmpresa" value="#{proveedoresController.selected.telefonoEmpresa}" title="#{agenda.CreateProveedoresTitle_telefonoEmpresa}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_telefonoEmpresa}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_emailContacto}" for="emailContacto" />
                        <p:inputText id="emailContacto" value="#{proveedoresController.selected.emailContacto}" title="#{agenda.CreateProveedoresTitle_emailContacto}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_emailContacto}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_domicilio}" for="domicilio" />
                        <p:inputText id="domicilio" value="#{proveedoresController.selected.domicilio}" title="#{agenda.CreateProveedoresTitle_domicilio}" required="true" requiredMessage="#{agenda.CreateProveedoresRequiredMessage_domicilio}"/>
                        <p:outputLabel value="#{agenda.CreateProveedoresLabel_idUsuarios}" for="idUsuarios" />
                        <p:selectOneMenu id="idUsuarios" value="#{proveedoresController.selected.idUsuarios}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_idUsuarios}">
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsuariosItem"
                                           itemValue="#{idUsuariosItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{proveedoresController.create}" value="#{agenda.Save}" update="display,:ProveedoresListForm:datalist,:growl" oncomplete="handleSubmit(args,'ProveedoresCreateDialog');"/>
                    <p:commandButton value="#{agenda.Cancel}" onclick="ProveedoresCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/proveedores/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProveedoresEditDlg" widgetVar="ProveedoresEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda.EditProveedoresTitle}">
            <h:form id="ProveedoresEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{proveedoresController.selected != null}">
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_idProveedores}" for="idProveedores" />
                        <p:inputText id="idProveedores" value="#{proveedoresController.selected.idProveedores}" title="#{agenda.EditProveedoresTitle_idProveedores}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_idProveedores}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{proveedoresController.selected.nombre}" title="#{agenda.EditProveedoresTitle_nombre}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_nombreContacto}" for="nombreContacto" />
                        <p:inputText id="nombreContacto" value="#{proveedoresController.selected.nombreContacto}" title="#{agenda.EditProveedoresTitle_nombreContacto}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_nombreContacto}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_telefonoContacto}" for="telefonoContacto" />
                        <p:inputText id="telefonoContacto" value="#{proveedoresController.selected.telefonoContacto}" title="#{agenda.EditProveedoresTitle_telefonoContacto}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_telefonoContacto}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_telefonoEmpresa}" for="telefonoEmpresa" />
                        <p:inputText id="telefonoEmpresa" value="#{proveedoresController.selected.telefonoEmpresa}" title="#{agenda.EditProveedoresTitle_telefonoEmpresa}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_telefonoEmpresa}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_emailContacto}" for="emailContacto" />
                        <p:inputText id="emailContacto" value="#{proveedoresController.selected.emailContacto}" title="#{agenda.EditProveedoresTitle_emailContacto}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_emailContacto}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_domicilio}" for="domicilio" />
                        <p:inputText id="domicilio" value="#{proveedoresController.selected.domicilio}" title="#{agenda.EditProveedoresTitle_domicilio}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_domicilio}"/>
                        <p:outputLabel value="#{agenda.EditProveedoresLabel_idUsuarios}" for="idUsuarios" />
                        <p:selectOneMenu id="idUsuarios" value="#{proveedoresController.selected.idUsuarios}" required="true" requiredMessage="#{agenda.EditProveedoresRequiredMessage_idUsuarios}">
                            <f:selectItem itemLabel="#{agenda.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsuariosItem"
                                           itemValue="#{idUsuariosItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{proveedoresController.update}" value="#{agenda.Save}" update="display,:ProveedoresListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ProveedoresEditDialog');"/>
                    <p:commandButton value="#{agenda.Cancel}" onclick="ProveedoresEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/proveedores/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{agenda.ListProveedoresTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ProveedoresListForm">
                <p:panel header="#{agenda.ListProveedoresTitle}">
                    <p:dataTable id="datalist" value="#{proveedoresController.items}" var="item"
                                 selectionMode="single" selection="#{proveedoresController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idProveedores}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_idProveedores}"/>
                            </f:facet>
                            <h:outputText value="#{item.idProveedores}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_nombreContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombreContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_telefonoContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefonoContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_telefonoEmpresa}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefonoEmpresa}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_emailContacto}"/>
                            </f:facet>
                            <h:outputText value="#{item.emailContacto}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_domicilio}"/>
                            </f:facet>
                            <h:outputText value="#{item.domicilio}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListProveedoresTitle_idUsuarios}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsuarios}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{agenda.Create}" actionListener="#{proveedoresController.prepareCreate}" update=":ProveedoresCreateForm" oncomplete="PF('ProveedoresCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{agenda.View}" update=":ProveedoresViewForm" oncomplete="PF('ProveedoresViewDialog').show()" disabled="#{empty proveedoresController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{agenda.Edit}" update=":ProveedoresEditForm" oncomplete="PF('ProveedoresEditDialog').show()" disabled="#{empty proveedoresController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{agenda.Delete}" actionListener="#{proveedoresController.destroy}" update=":growl,datalist" disabled="#{empty proveedoresController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/proveedores/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProveedoresViewDlg" widgetVar="ProveedoresViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda.ViewProveedoresTitle}">
            <h:form id="ProveedoresViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{proveedoresController.selected != null}">
                        <h:outputText value="#{agenda.ViewProveedoresLabel_idProveedores}"/>
                        <h:outputText value="#{proveedoresController.selected.idProveedores}" title="#{agenda.ViewProveedoresTitle_idProveedores}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_nombre}"/>
                        <h:outputText value="#{proveedoresController.selected.nombre}" title="#{agenda.ViewProveedoresTitle_nombre}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_nombreContacto}"/>
                        <h:outputText value="#{proveedoresController.selected.nombreContacto}" title="#{agenda.ViewProveedoresTitle_nombreContacto}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_telefonoContacto}"/>
                        <h:outputText value="#{proveedoresController.selected.telefonoContacto}" title="#{agenda.ViewProveedoresTitle_telefonoContacto}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_telefonoEmpresa}"/>
                        <h:outputText value="#{proveedoresController.selected.telefonoEmpresa}" title="#{agenda.ViewProveedoresTitle_telefonoEmpresa}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_emailContacto}"/>
                        <h:outputText value="#{proveedoresController.selected.emailContacto}" title="#{agenda.ViewProveedoresTitle_emailContacto}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_domicilio}"/>
                        <h:outputText value="#{proveedoresController.selected.domicilio}" title="#{agenda.ViewProveedoresTitle_domicilio}"/>
                        <h:outputText value="#{agenda.ViewProveedoresLabel_idUsuarios}"/>
                        <h:outputText value="#{proveedoresController.selected.idUsuarios}" title="#{agenda.ViewProveedoresTitle_idUsuarios}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{agenda.Close}" onclick="ProveedoresViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>